"""empty message

Revision ID: 5026922852e0
Revises: 
Create Date: 2024-10-25 22:56:48.424841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5026922852e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('const', sa.Enum('INSTANT_SELL_PERC', 'MAX_INSTANT_SELL', 'FEE_WITHDRAWAL_TRON', 'FEE_WITHDRAWAL_TON', 'FEE_SWAP', 'FEE_BUY', 'FEE_SELL', name='const'), nullable=False),
    sa.Column('value', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('const')
    )
    op.create_table('numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('number')
    )
    op.create_table('start_utime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_utime', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', name='userstatus'), nullable=False),
    sa.Column('ton_balance', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('usdt_balance', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('users_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.Enum('TON', 'USDT', name='transactiontoken'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('from_token', sa.Enum('TON', 'USDT', name='swaptoken'), nullable=False),
    sa.Column('from_amount', sa.Float(), nullable=False),
    sa.Column('to_token', sa.Enum('TON', 'USDT', name='swaptoken'), nullable=False),
    sa.Column('to_amount', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_usernames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username_id'], ['usernames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.Enum('TON', 'USDT', name='transactiontoken'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_number_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_number_id'], ['users_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_usernames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_username_id'], ['users_usernames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_usernames')
    op.drop_table('market_numbers')
    op.drop_table('users_withdrawals')
    op.drop_table('users_usernames')
    op.drop_table('users_swaps')
    op.drop_table('users_numbers')
    op.drop_table('users_deposits')
    op.drop_table('users_addresses')
    op.drop_table('users')
    op.drop_table('usernames')
    op.drop_table('start_utime')
    op.drop_table('numbers')
    op.drop_table('constants')
    # ### end Alembic commands ###
